version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres_db
    environment:
      POSTGRES_DB: coffee_machine
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: coffee_machine_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/coffee_machine?currentSchema=coffee_machine
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: true
    ports:
      - "8090:8090"
    depends_on:
      - postgres


